#!/bin/bash

# Nodes according to the official list: https://protonvpn.com/vpn-servers#secure-core
SERVERS=(
  "CH-AT#2"
  "SE-EE#1"
  "CH-EE#2"
  "CH-LU#2"
  "IS-NO#1"
  "SE-NO#1"
  "CH-NO#2"
  "SE-FI#1"
  "CH-FI#2"
  "SE-RO#1"
  "CH-RO#2"
)

case "$1" in
  "-l") # list
    printf "%s\n" "${SERVERS[@]}"
    ;;

  "-d") # disconnect
    echo "Disconnecting from ProtonVPN..."
    protonvpn disconnect
    ;;

  "-m") # menu
    PS3="Select a server number (or 'c' to cancel): "
    select s in "${SERVERS[@]}"; do
      if [[ "$REPLY" == "c" ]]; then
        echo "Connection attempt cancelled."
        exit 0
      elif [[ -n "$s" ]]; then
        echo "Connecting to $s..."
        protonvpn connect "$s"
        break
      else
        echo "Invalid option: $REPLY. Please choose a number from the list or 'c'."
      fi
    done
    ;;

  *)
    INDEX=$(( RANDOM % ${#SERVERS[@]} ))
    SELECTED="${SERVERS[$INDEX]}"
    echo "Selected Secure Core Server: $SELECTED"
    protonvpn connect "$SELECTED"
    ;;
esac